Import("*")

# Expected Imports:
# - env
# - ecp5_soc_dir
# - neorv32_wrapper

env.Append(
    VPATH = [
        ecp5_soc_dir.Dir("rtl").srcnode(),
    ]
)

soc_ast = env.Command(
    "top.json",
    ["top.v", neorv32_wrapper],
    "yosys $YOSYSFLAGS -p '" +
    " read_verilog $VFLAGS $_VINCFLAGS $_VDEFFLAGS $SOURCES;" +
    " synth_ecp5 -top top -json $TARGET" +
    "'"
)

Return("soc_ast")
