Import("*")

# First, build an elf file.
blinky_elf = env.Program("blinky.elf", ["main.c"])

# Then, convert that elf file into a binary file.
blinky_bin = env.Command(
    "blinky.bin",
    [blinky_elf],
    "$OBJCOPY -I elf32-little $SOURCE -O binary $TARGET",
    cmdstr = "objcopy $TARGET"
)

# Finally, convert that binary file into a text file with it's contents written 32 bits at a time in hex.
blinky = env.Command(
    "blinky.init",
    [blinky_bin],
    "xxd -ps -c 4 $SOURCE > $TARGET"
)

Return("blinky")
