Import("*")

blinky_elf = env.Program("blinky.elf", ["main.c"])

blinky_bin = env.Command(
    "blinky.bin",
    [blinky_elf],
    "$OBJCOPY -I elf32-little $SOURCE -O binary $TARGET",
    cmdstr = "objcopy $TARGET"
)

Return("blinky_bin")
