Import("*")

# First, build an elf file.
uart_elf = env.Program("uart.elf", ["main.c"])

# Then, convert that elf file into a binary file.
uart_bin = env.Command(
    "uart.bin",
    [uart_elf],
    "$OBJCOPY -I elf32-little $SOURCE -O binary $TARGET",
    cmdstr = "objcopy $TARGET"
)

# Finally, convert that binary file into a text file with it's contents written 32 bits at a time in hex.
uart = env.Command(
    "uart.init",
    [uart_bin],
    "xxd -ps -c 4 $SOURCE > $TARGET"
)

Return("uart")
