Import("*")

bootrom_elf = env.Program("bootrom.elf", ["start.S"])

bootrom_bin = env.Command(
    "bootrom.bin",
    [bootrom_elf],
    "$OBJCOPY -I elf32-little $SOURCE -O binary $TARGET",
    cmdstr = "objcopy $TARGET"
)

bootrom_init = env.Command(
    "bootrom.init",
    [bootrom_bin],
    "xxd -ps -c 4 $SOURCE > $TARGET"
)

Return("bootrom_init")

