Import("*")

# First, build an elf file.
bootrom_elf = env.Program("bootrom.elf", ["start.S"])

# Then, convert that elf file into a binary file.
bootrom_bin = env.Command(
    "bootrom.bin",
    [bootrom_elf],
    "$OBJCOPY -I elf32-little $SOURCE -O binary $TARGET",
    cmdstr = "objcopy $TARGET"
)

# Finally, convert that binary file into a text file with it's contents written 32 bits at a time in hex.
bootrom_init = env.Command(
    "bootrom.init",
    [bootrom_bin],
    "xxd -ps -c 4 $SOURCE > $TARGET"
)

Return("bootrom_init")

