Import("*")

m1_elf = env.Program("m1.elf", ["main.c"])

m1_bin = env.Command(
    "m1.bin",
    [m1_elf],
    "$OBJCOPY -I elf32-little $SOURCE -O binary $TARGET",
    cmdstr = "objcopy $TARGET"
)

m1_dfu = env.DfuSuffix("m1.dfu", m1_bin)

