Import("*")

name = "walleos"
sources = ["main.c"]

env.Append(CFLAGS="-Wno-format")

elf = env.Program(f"{name}.elf", sources)

binary = env.Command(
    f"{name}.bin",
    [elf],
    "$OBJCOPY -I elf32-little $SOURCE -O binary $TARGET",
    cmdstr = "objcopy $TARGET"
)

dfu = env.DfuSuffix(f"{name}.dfu", binary)
